include:
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: studio-rpc-usb-uart
    artifact-name: nice_corne_left_oled
  - board: nice_nano_v2
    shield: corne_right nice_oled
    artifact-name: nice_corne_right_oled
  - board: nice_nano_v2
    shield: settings_reset
